---
- name: Configuracion inicial VM
  hosts: servers
  become: true
  
  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes
        upgrade: safe

    - name: Unir VM a Tailscale
      shell: >
        tailscale up
        --auth-key={{ tailscale_auth_key }} 

    - name: Configurar Doppler
      shell: doppler configure set token {{ doppler_token }}
      become_user: brian

    - name: Copiar Docker Compose
      copy:
        src: docker-compose.yml
        dest: /home/brian/app/docker-compose.yml
        owner: brian
        group: brian
        mode: '0644'
        
    - name: Remover Caddyfile corrupto si es un directorio
      file:
        path: /home/brian/app/Caddyfile
        state: absent
      
    - name: Copiar Caddyfile
      copy:
        src: Caddyfile
        dest: /home/brian/app/Caddyfile
        owner: brian
        group: brian
        mode: '0644'

    - name: Levantar y Actualizar Contenedores
      become_user: brian
      environment:
        DOPPLER_AUTH_TOKEN: "{{ doppler_token }}"
      shell: >
        doppler run -- sh -c "docker compose pull && docker compose up -d --force-recreate"
      args:
        chdir: /home/brian/app
  
  handlers:
    - name: Reiniciar SSH
      service:
        name: ssh
        state: restarted  