name: Build Docker Image

on:
  push:
    branches: [main]
    paths-ignore:
      - 'Infrastructure/**'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Crear llave SSH temporal
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Restore Ansible Inventory from Cache
          uses: actions/cache/restore@v4
          with:
            path: Ansible/inventory.ini
            # Buscamos primero si existe para el commit actual (por si acaso)
            key: ansible-inventory-cache-${{ github.sha }}
            # Si no existe, recupera el más reciente que coincida con el prefijo
            restore-keys: |
              ansible-inventory-cache-

      # Verificación de seguridad por si acaso el caché llegara a estar vacío
      - name: Check Inventory Existence
        run: |
          if [ ! -f Ansible/inventory.ini ]; then
            echo "Error: El archivo Ansible/inventory.ini no está en el caché. Ejecuta el pipeline de Terraform primero."
            exit 1
          fi    

      - name: Ejecutar Ansible
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
          DOPPLER_AUTH_TOKEN: ${{ secrets.DOPPLER_AUTH_TOKEN }}
        run: |
          cd Ansible
          ansible-playbook playbook.yml \
          -i inventory.ini \
          --private-key ~/.ssh/id_rsa \
          -e "doppler_token=${DOPPLER_AUTH_TOKEN}" \
          -e "tailscale_auth_key=${TAILSCALE_AUTH_KEY}"     