name: Terraform

on:
  push:
    branches: [main]
    paths:
      - 'Infrastructure/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Infrastructure
    env:
      TF_IN_AUTOMATION: "true"
      TF_VAR_hcloud_token: ${{ secrets.hcloud_token }}
      TF_VAR_hcp_client_id: ${{ secrets.HCP_CLIENT_ID }}
      TF_VAR_hcp_client_secret: ${{ secrets.HCP_CLIENT_SECRET }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Cache Ansible Inventory
        uses: actions/cache/save@v4
        with:
          path: Ansible/inventory.ini
          key: ansible-inventory-cache-${{ github.sha }}
